### ISSUE TITLE
Possible to upgrade electron to support darwin-arm64?

### ISSUE THREAD

**Issue by njusang** [AgoraIO-Community/CloudClass-Desktop#66]
Hi maintainers,

With the current version of  `electron` 
https://github.com/AgoraIO-Community/CloudClass-Desktop/blob/5d6c97ac7032dfddab4bc807a1d7ce4a745f9f38/packages/agora-electron-edu-demo/package.json#L61

I find it hard to install `electron` on my `MacBook Pro (13-inch, M1, 2020)`, with the following output
```
➜  CloudClass-Desktop git:(release/apaas/1.1.2) ✗ node ./node_modules/electron/install.js 
(node:43866) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v7.1.14/electron-v7.1.14-darwin-arm64.zip
    at EventEmitter.<anonymous> (/Users/syx/Code/CloudClass-Desktop/node_modules/@electron/get/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:375:28)
    at module.exports (/Users/syx/Code/CloudClass-Desktop/node_modules/@electron/get/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/syx/Code/CloudClass-Desktop/node_modules/@electron/get/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:482:26)
    at ClientRequest.emit (events.js:387:35)
    at ClientRequest.origin.emit (/Users/syx/Code/CloudClass-Desktop/node_modules/@electron/get/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:43866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:43866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by plutoless** [comment]
you may try upgrading to electron 12. i guess you are using M1?

**Comment by njusang** [comment]
close this since it's duplicated with #67

**Comment by njusang** [comment]
> you may try upgrading to electron 12. i guess you are using M1?

that's true, I'm using `MacBook Pro (13-inch, M1, 2020)`
